sudo: required
dist: bionic
language: csharp
mono: none
dotnet:5.0
services: docker
before_install:
  - cd 01_Rest.Net5/
  - echo "Estamos no folder rest1"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USARNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest.net5:latest $DOCKER_USARNAME/rest.net5:$TRAVIS_JOB_ID;
    docker tag rest.net5-db:latest $DOCKER_USARNAME/rest.net5-db:$TRAVIS_JOB_ID;
    docker push $DOCKER_USARNAME/rest.net5:$TRAVIS_JOB_ID;
    docker push $DOCKER_USARNAME/rest.net5-db:$TRAVIS_JOB_ID;
  on:
    branch: master
 notifications:
   email: false